### ISSUE TITLE
Stuttering with SR6

### ISSUE THREAD

**Issue by dvojas** [Yoooi0/MultiFunPlayer#56]
I have recently built SR6 and I am experiencing quite heavy stuttering with MFP. I am using the latest version 1.20. I have seen on the Tempest Server discord that Giardino had recently problem with stuttering and it was fixed, but it seems that I have a different issue.

Stuttering is more visible with 330hz communication, but even on 50hz it stutters like every 10s with very big movements which are quite dangerous. I am using serial connection with CP210x driver v11. Switching Tcode versions does not help. Change of interpolation does not help.

Stutters with every player (tried MPC, MPV, DeoVR, Whirligig), also stutters with JFP 4.0, but it is smooth as butter with XTPlayer v0.283b. Which brings me to believe that my OSR6 and servos are actually not the problem.

Please let me know if I can help to somehow catch the bug - logs, video etc.

**Comment by dvojas** [comment]
If I send L00000I1000 or L09999I1000 manually via serial monitor it does not stutter.

**Comment by Yoooi0** [comment]
For me serial is super smooth so I would need trace logs.
Set the log level to `Trace` in settings accessed via cog button on top of the window, then connect video and serial, reproduce the stutter issues, close MFP and post logs (you can also DM me the logs on discord).

**Comment by Yoooi0** [comment]
Fixed: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/2000702458
The commit that broke it was just after I used MFP last time.

**Comment by dvojas** [comment]
The build did not fix the issue :( new logs here.
[Logs.zip](https://github.com/Yoooi0/MultiFunPlayer/files/8292330/Logs.zip)

**Comment by Yoooi0** [comment]
That big stutters are I think a firmware issue, IIRC the fix was to append a dummy command.
So try adding a pattern motion provider to V0 so that it is forced to always update.

**Comment by dvojas** [comment]
![image](https://user-images.githubusercontent.com/12684793/158895139-5bc18e9b-8851-454c-a660-c30666cac071.png)

even if I just start motion provider as sine when video is paused the stuttering is there :(

**Comment by Yoooi0** [comment]
Do it on V0/V1/L3 so its appended after L0

**Comment by dvojas** [comment]
OMG! that really works! Thank you very much for assistance! This bug/issue can be closed. I am joining your patreon, that is the least I can do to say thank you.

**Comment by Yoooi0** [comment]
Thanks! Just to be sure set the motion provider on V0 to `Triangle` and speed it up a bit so it is guaranteed to be updated each tick. Sine has slow spots on top/bottom and it might be optimized to not be sent.
